### ISSUE TITLE
Having a hard time building this - something about KlakMath?

### ISSUE THREAD

**Issue by gpvillamil** [keijiro/GeoVfx#1]
Thank you for this amazing work! It is a fantastic way to learn about Unity and VFXGraph.

Unfortunately, I have a problem. When I open the GeoVfx project, I get:

```
Unity Package Manager Error

An error occurred while resolving packages:
  Project has invalid dependencies:
    jp.keijiro.klak.math: Error when executing git command. xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun


A re-import of the project may be required to fix the issue or a manual modification of /Users/gianpablo/Documents/Unity Projects/GeoVfx/Packages/manifest.json file.

Click on Retry to relaunch Unity and reopen your project.

Click on Continue to launch Unity.  Some or all packages may not be imported which may cause compilation errors.
```

I downloaded the Klakmath repo, but I can't seem to import it as a package.

**Comment by gpvillamil** [comment]
Never mind, command line tools were not correctly installed. Everything is working now.

I fixed this by running

`xcode-select --install`

**Comment by tracer8** [comment]
> Never mind, command line tools were not correctly installed. Everything is working now.
> 
> I fixed this by running
> 
> `xcode-select --install`

This work like a charm. THank you!
