### ISSUE TITLE
UnityEngine.VFX.Utility error

### ISSUE THREAD

**Issue by rmib200** [keijiro/GeoVfx#2]
Hi, while trying to run the project I encountered a couple of errors that I can't solve. 

- error CS1061: 'VisualEffect' does not contain a definition for 'HasGraphicsBuffer' and no accessible extension method 'HasGraphicsBuffer' accepting a first argument of type 'VisualEffect' could be found (are you missing a using directive or an assembly reference?)

- error CS1061: 'VisualEffect' does not contain a definition for 'SetGraphicsBuffer' and no accessible extension method 'SetGraphicsBuffer' accepting a first argument of type 'VisualEffect' could be found (are you missing a using directive or an assembly reference?)

It seems that both errors has something to do with a dependency called UnityEngine.VFX.Utility. I searched the web for info but I haven't been able to find it. Do you know what can be done about it? I'm very new to VFX.

**Comment by keijiro** [comment]
Which Unity version are you using? This project requires Unity 2021.2.

**Comment by rmib200** [comment]
Noted. Will try with that version. I was using a 2020 LTS version.

**Comment by keijiro** [comment]
Then I'm sure that it will be solved by using 2021.2.

I'm closing this issue now. Please reopen the issue if it still reproduces with 2021.2.
